# SonarQube Project Identification
sonar.projectKey=catchmydream
sonar.projectName=catchmydream
sonar.projectVersion=1.0

# Path to sources
sonar.sources=.
sonar.language=js

# Exclude dependencies and build directories from analysis
sonar.exclusions=**/node_modules/**, .next/**, out/**, coverage/**, prisma/**, public/**, tsconfig.json, next.config.ts

# Host URL (default local instance)
sonar.host.url=http://localhost:9000

# Source Encoding
sonar.sourceEncoding=UTF-8
